config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#index'

  post "/api/checkin" => "api#add_checkin"

  post "/api/reasons" => "api#add_reason"
  put "/api/reasons/:id" => "api#update_reason"
  post "/api/reasons/:id/delete" => "api#delete_reason"

  post "/api/users" => "api#add_user"
  put "/api/users/:id" => "api#update_user"
  get "/api/users/:id/reasons" => "api#get_user_reasons"
  post "/api/users/:id/delete" => "api#delete_user"

  get "/:school" => "pages#checkin"
  get "/:school/admin" => "pages#admin"

end

app/models/reason.rb
# == Schema Information
#
# Table name: reasons
#
#  id         :integer          not null, primary key
#  school_id  :integer
#  text       :text
#  created_at :datetime
#  updated_at :datetime
#

class Reason < ActiveRecord::Base
	validates :school, :text, presence: true, allow_nil: false, allow_blank: false

	belongs_to :school

	has_many :reason_users
   	has_many :users, through: :reason_users

	def name
		text
	end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(255)
#  is_admin               :boolean
#  school_id              :integer
#  honorific              :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   belongs_to :school
   validates :school, :name, :honorific, presence: true, allow_nil: false, allow_blank: false

   has_many :checkins
   has_many :reason_users
   has_many :reasons, through: :reason_users
end

app/views/pages/admin.html.erb
<div class="row">
  <br/><br/>
  <% if current_user.is_admin == true %>
  <div class="btn-group pull-right" data-toggle="buttons">
    <label class="btn btn-primary active">
      <input type="radio" name="options" id="checkins_btn" autocomplete="off" checked>Checkins
    </label>
    <label class="btn btn-primary">
      <input type="radio" name="options" id="settings_btn" autocomplete="off">Settings
    </label>
    <label class="btn btn-primary">
      <input type="radio" name="options" id="users_btn" autocomplete="off">Users
    </label>
  </div>
  <% end %>

  <div id="checkins" style="display:none">
    <table class="table table-striped">
      <thead>
        <th>Type</th>
        <th>Name</th> 
        <th>Visting</th>
        <th>Reason</th>
        <th>Student Badge ID</th>
        <th>Child Name</th>
        <th>Check in Time</th>
      </thead>
      <tbody>
        <% @checkins.each do |checkin| %>
          <tr>
            <td><%= checkin.name %></td>
            <td><%= checkin.is_student ? "Student" : "Parent" %></td>
            <td><%= checkin.user.name %></td>
            <td>
              <%= checkin.custom_reason ? checkin.reason_text : checkin.reason.text %>
            </td>
            <td><%= checkin.is_student ? checkin.badge_id : "" %></td>
            <td><%= checkin.is_student ? "" : checkin.child_name %></td>
            <td><%= checkin.created_at.strftime("%m/%d/%y %I:%M %p")%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if current_user.is_admin == true %>
  <div id="settings" style="display:none">
    <h4>Reasons</h4>
    <table class="table table-striped">
      <thead>
        <th>Text</th>
        <th>Users</th>
        <th></th>
      </thead>
      <tbody>
        <% @reasons.each do |reason| %>
          <tr>
            <td><a href="#" id="text_<%= reason.id %>" class="editable" data-type="textarea" data-resource="reason" data-name="text" data-url="/api/reasons/<%= reason.id %>" data-original-title="Enter Reason Text"><%= reason.text %></a></td>
            <td>
              <a href="#" id="users_<%= reason.id%>" class="editable" data-type="checklist" data-url="/api/reasons/<%= reason.id %>" data-title="Select Users" data-resource="reason" data-name="user_ids" data-source="<%= @users.map{|a| {"value" => a.id, "text" => a.name}}.to_json %>" data-value="[<%= reason.users.map{|a|a.id}.join(",") %>]"><%= reason.users.map{|a|a.name}.join("<br/>").html_safe %></a>
            </td>
            <td>
              <button class="btn btn-danger delete_reason pull-right" id="delete_<%= reason.id %>">X</button>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>
            <input type="text" class="form-control" id="reason_text" placeholder = "New Reason"/>
          </td>
          <td>
            <button class="btn btn-primary pull-right" id="new_reason">Add Reason</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div id="users" style="display:none">
    <table class="table table-striped">
      <thead>
        <th>Title</th>
        <th>Name</th>
        <th>Role</th>
        <th>Email</th>
        <th>Reasons For Visiting</th>
        <th></th>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><a href="#" id="title_<%= user.id%>" class="editable-title" data-type="select" data-url="/api/users/<%= user.id %>" data-title="Select Title" data-resource="user" data-name="honorific"><%= user.honorific %></a></td>
            <td><a href="#" id="name_<%= user.id%>" class="editable" data-type="text" data-url="/api/users/<%= user.id %>" data-title="Name" data-resource="user" data-name="name"><%= user.name %></a></td>
            <td>
              <% if current_user.id != user.id %>
                <a href="#" id="_<%= user.id%>" class="editable-is-admin" data-type="select" data-url="/api/users/<%= user.id %>" data-title="Role" data-resource="user" data-name="is_admin"><%= user.is_admin ? "Admin" : "User" %></a>
              <% else %>
                <%= user.is_admin ? "Admin" : "User" %>
              <% end %>
            </td>
            <td>
                <a href="#" id="title_<%= user.id%>" class="editable" data-type="text" data-url="/api/users/<%= user.id %>" data-title="Select Title" data-resource="user" data-name="email"><%= user.email %></a>
            </td>
            <td>
              <a href="#" id="reasons_<%= user.id%>" class="editable" data-type="checklist" data-url="/api/users/<%= user.id %>" data-title="Select Reasons" data-resource="user" data-name="reason_ids" data-source="<%= @reasons.map{|a| {"value" => a.id, "text" => a.text}}.to_json %>" data-value="[<%= user.reasons.map{|a|a.id}.join(",") %>]"><%= user.reasons.map{|a|a.text}.join("<br/>").html_safe %></a>
            </td>
            <td>
              <% if current_user.id != user.id %>
                <button class="btn btn-danger delete_user pull-right" id="delete_<%= user.id %>">X</button>
              <% end %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>
            <select class ="form-control" id="honorific">
              <option value="">Title</option>
              <option value="Dr.">Dr.</option>
              <option value="Mr.">Mr.</option>
              <option value="Mrs.">Mrs.</option>
              <option value="Ms.">Ms.</option>
            </select>
          </td>
          <td>
            <input type="text" class="form-control" placeholder="Name" id="name" />
          </td>
          <td>
            <select class ="form-control" id="role">
              <option value="">Role</option>
              <option value="true">Admin</option>
              <option value="false">User</option>
            </select>
          </td>
          <td>
            <input type="email" placeholder = "Email" id="email" class="form-control" />
          </td>
          <td>
          </td>
          <td>
            <button class="btn btn-primary pull-right" id="new_user">Add User</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <% end %>
</div>

app/views/pages/checkin.html.erb
<div class="row">
	<center>
		<h2><%= @school.name %></h2>
		<h3>Counselor Checkin</h3><br/>
	</center>
</div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<b>I am a &nbsp;</b>
		<div class="radio-inline">
		  <label><input type="radio" name="optradio" value="student">Student</label>
		</div>
		<div class="radio-inline">
		  <label><input type="radio" name="optradio" value="parent">Parent</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<label for="name">Name</label>
		<input type="text" id="name" name="name" class="form-control" />
	</div>
</div>
<div class="row" id="student-questions" style="display: none">
	<div class="col-sm-4 col-sm-offset-4">
		<label for="badge">Badge ID</label>
		<input type="text" id="badge" name="badge" class="form-control" />
	</div>
</div>
<div class="row" id="parent-questions" style="display: none">
	<div class="col-sm-4 col-sm-offset-4">
		<label for="student-name">Student's Name</label>
		<input type="text" id="student-name" name="student-name" class="form-control" />
	</div>
</div>
<div class="row other-questions" style="display: none">
	<div class="col-sm-4 col-sm-offset-4">
		<label for="visiting">I'm here to see</label>
		<select class="form-control" name="visiting" id="visiting">
			<option value=""></option>
			<% @counselors.each do |counselor| %>
				<option value="<%= counselor.id %>"><%= counselor.honorific + " " + counselor.name %></option>
			<% end %>
		</select>
	</div>
</div>
<div class="row" id="aboutWrapper" style="display: none">
	<div class="col-sm-4 col-sm-offset-4">
		<label for="reason">About</label>
		<select class="form-control" name="reason" id="reason">
			<option value=""></option>
			<% @reasons.each do |reason| %>
				<option value="<%= reason.id %>"><%= reason.text %></option>
			<% end %>
			<option value="other">Other<other>
		</select>
		<textarea id="other-text" class="form-control" placeholder="Describe why you are visiting us today" style="display:none"></textarea>
	</div>
</div>
<div class="row other-questions" style="display: none">
	<div class="col-sm-4 col-sm-offset-4">
		<button class="btn btn-primary form-control" id="checkin-submit">Check In</button>
	</div>
</div>

app/views/pages/index.html.erb
<center>
	<h1>Counselor Checkin App</h1>
	Select your school from the list below to check in
	<div>
		<% @schools.each do |school| %>
			<a href="/<%= school.url %>"><%= school.name %></a><br/> 
		<% end %>
	</div>
</center>